# Generated by Django 3.2.9 on 2021-11-04 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('todoapp', '0002_auto_20211104_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 4, 9, 56, 29, 448391)),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
