# Generated by Django 3.2.9 on 2021-11-05 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20211104_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 11, 5, 13, 4, 38, 532490)),
        ),
    ]
